stages:
  download_data:
    cmd: python download_data.py
    deps:
    - download_data.py
    - params.yaml
    outs:
    - data/iris.csv
  train_model:
    cmd: python train_model.py
    deps:
    - data/iris.csv
    - params.yaml
    - train_model.py
    outs:
    - models/model.pkl
    metrics:
    - metrics.json:
        cache: false
